#
# Logger extend configuration
#

obj-$(CONFIG_LOG_SWITCH)	+= log_switch.o
obj-$(CONFIG_LOG_EXCEPTION)	+= log_exception.o
obj-$(CONFIG_LOG_JANK)	        += log_jank.o
obj-$(CONFIG_HUAWEI_NFF)        += nff_log_event.o
obj-$(CONFIG_HUAWEI_GOLDENEYE) += goldeneye/
obj-$(CONFIG_PROC_LOGUSERTYPE) += log_usertype/
