##############################################
#     Make file of OV8856 camera sensor
##############################################

EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6210_CAMERA_OV8856_SUNNY) += ov8856_sunny.o

#################### END #####################