##############################################
#     Make file of HI843S camera sensor
##############################################

EXTRA_CFLAGS += -fno-pic
obj-$(CONFIG_HI6210_CAMERA_HI843S_OFILM) += hi843s_ofilm.o

#################### END #####################
