subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/include/nv/tl/drv/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/include/nv/tl/oam/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/include/nv/tl/lps/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/include/phy/lphy/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/config/nvim/include/gu/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/
subdir-ccflags-y                        += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/include_gu/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/include/drv/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/modem/drv/common/include/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM)/soc/
subdir-ccflags-y   			+= -I$(BALONG_TOPDIR)/platform/$(CFG_PLATFORM)/

obj-$(CONFIG_HISI_BALONG_MODEM_HI3630)  += drv/
obj-$(CONFIG_HISI_BALONG_MODEM_HI3630)  += oam/ ps/ taf/
