#=============================================================================
#  w62358 DTS2011072902818 hardware self adapter
#  m00182086 DTS2011103102253 sync TI sensor driver
#  hkf20596  DTS2011092500027 platform gpio unite
#  l00186656 DTS2011120701242 unification scheme of regulators
#=============================================================================


obj-y   += NXP_PN547_64/
obj-y   += nfc_bcm20793/

