obj-$(CONFIG_HUAWEI_CHARGER)	+= charger/
obj-$(CONFIG_HUAWEI_KSTATE)	+= hw_kstate/
obj-$(CONFIG_INPUT_HW_ATE)	+= ate/
obj-$(CONFIG_HUAWEI_BASTET)	+= bastet/
obj-$(CONFIG_HUAWEI_SMPL)	+= smpl/
obj-$(CONFIG_HUAWEI_LP8754)	+= cpu_buck/
obj-$(CONFIG_HUAWEI_MSG_POLICY) += msgnotify/
