#ifndef __SOC_BBP_MASTER_INTERFACE_H__
#define __SOC_BBP_MASTER_INTERFACE_H__ 

#define SOC_BBPMASTER_REG_ADDR(base,offset) ((base)+(offset))


#define W_BBP_MASTER_RPT_CLR_HIGH_VALUE (0x00000001)


#define W_BBP_MASTER_ISR_SHIELD_VALUE (0x00000001)


#define W_BBP_MASTER_ISR_UNSHIELD_VALUE (0x0)


#define W_BBP_MASTER_ISR_WL_MASK_VALUE (0x00000001)


#define W_BBP_MASTER_ISR_YL_MASK_VALUE (0x00000002)


#define W_BBP_MASTER_ISR_TIMER_MASK_VALUE (0x00000004)


#define W_BBP_MASTER_ISR_BUS_ERROR_MASK_VALUE (0x00000008)


#define W_BBP_MASTER_ISR_MAIN_STEM_OVETIME_MASK_VALUE (0x00000010)


#define W_BBP_MASTER_ISR_SUB_STEM_OVETIME_MASK_VALUE (0x00000020)


#define W_BBP_MASTER_ISR_MAIN_HSDPA_MASK_VALUE (0x00000040)


#define W_BBP_MASTER_ISR_SUB_HSDPA_MASK_VALUE (0x00000080)


#define W_BBP_MASTER_TB_HEAD_SIZE_VALUE (0x10000000)


#define W_BBP_MASTER_RPT_WATER_LINE_VALUE (0xFFFFFFFF)


#define W_BBP_MASTER_RPT_OVERTIME_DEFAULT_VALUE (0x00001C80)


#define W_BBP_MASTER_MODE_FG_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9400)


#define W_BBP_MASTER_RPT_CLR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9404)


#define W_BBP_MASTER_HEAD_BUFFER_BASE_ADDR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9408)



#define W_BBP_MASTER_HEAD_BUFFER_SIZE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x940C)


#define W_BBP_MASTER_DATA_BUFFER_BASE_ADDR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9410)

#define W_BBP_MASTER_DATA_BUFFER_SIZE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9414)


#define W_BBP_MASTER_HSD_RPT_WATERLINE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9418)


#define W_BBP_MASTER_HSD_RPT_ALARMLINE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x941C)



#define W_BBP_MASTER_HSD_RPT_OVERTIME_VALUE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9420)


#define W_BBP_MASTER_HSD_RPT_SUB_PULSE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9424)


#define W_BBP_MASTER_HSD_RPT_SUB_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9428)


#define W_BBP_MASTER_HSD_RPT_TB_CNT_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x942C)


#define W_BBP_MASTER_HEAD_BUFFER_WR_INDEX_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9430)


#define W_BBP_MASTER_HSD_RPT_TB_CNT_INIT_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x9460)


#define W_BBP_MASTER_HSD_RPT_TB_CNT_CLR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x94A8)


#define W_BBP_MASTER_HEAD_BUFFER_OFFSET_ADDR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x94A0)


#define W_BBP_MASTER_DATA_BUFFER_OFFSET_ADDR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0x94A4)



#define W_BBP_MASTER_ISR_STATE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0xC0)


#define W_BBP_MASTER_ISR_MASK_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0xC4)


#define W_BBP_MASTER_ISR_ENABLE_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0xC8)


#define W_BBP_MASTER_ISR_CLR_REG(BaseAddr) SOC_BBPMASTER_REG_ADDR(BaseAddr, 0xCC)

#endif
