# maxim smartPA driver

obj-y	+= max98925/
obj-y	+= speakerID/
obj-y	+= anc_hs/
obj-y	+= tfa9895/
obj-y	+= earpiece_pa/
obj-y	+= dts_eagle/
obj-y	+= tpa2028_spk_l/
obj-y	+= tpa2028_spk_r/
obj-y	+= ad45257/
