subdir-ccflags-y                        += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/
subdir-ccflags-y                        += -I$(BALONG_TOPDIR)/config/product/$(OBB_PRODUCT_NAME)/config/include_gu/
subdir-ccflags-y        += -I$(BALONG_TOPDIR)/ap/platform/$(CFG_PLATFORM)/
subdir-ccflags-y        += -I$(BALONG_TOPDIR)/ap/platform/$(CFG_PLATFORM)/soc/

obj-y += gu/ lt/

