#
# Makefile for huawei's oam driver
#
#android4.2 cross-compile support module must add the follow options!
#EXTRA_CFLAGS += -DMODULE -fno-pic
#MODFLAGS = -DMODULE -fno-pic

obj-$(CONFIG_OAM_DRV)	+= oamdrv.o
oamdrv-objs		:= oam_drv.o

