##############################################
#     Make file of imx219 camera sensor
##############################################

EXTRA_CFLAGS += -fno-pic 
obj-$(CONFIG_HI6210_CAMERA_IMX219_SUNNY) += imx219_sunny.o

#################### END #####################
