ifdef CONFIG_ARCH_HI6XXX
ifeq ($(TARGET_ARM_TYPE), arm64)
obj-y			+= mali4_64/
else
obj-y			+= mali4_32/
endif
endif

ifdef CONFIG_HISI_3635
obj-y                   += r8p0-01dev0/
endif

ifdef CONFIG_ARCH_HI3630
obj-y                   += r8p0-01dev0/
endif
